```{sh vars, include=FALSE}
REPO=$(cat .git/config | grep https | awk '{print $3}' | sed -e 's/\.git//g')
source ./.env
IMAGE=${DOCKER_USER}/${IMAGE_NAME}:${TAG}
```

# A docker image to knit Rmd files

A alpine-based docker image with

- `r version[['version.string']]` (with renv, knitr and reticulate)
- `r system('python --version', intern=TRUE)`
- `r system('poetry --version', intern=TRUE)`

The image might be useful to include output of codes in README.md. For instance, this README.md is generated by `knitr::knit`ing README.rmd.

(For Docker Hub) This image is maintained at
```{sh remote-repo, echo=FALSE, comment=""}
<<vars>>
echo ${REPO}
```

## Usage

The following command knits README.rmd at your project top to produce README.md.
```{sh usage, echo=FALSE, comment=""}
<<vars>>
echo "docker run -it --rm -v \${PWD}:${HOME_CONTAINER}/workdir ${IMAGE} Rscript -e \"knitr::knit('README.rmd')\""
```

## Install

The images is available at Docker hub.

```{sh docker-pull, echo=FALSE, comment=""}
<<vars>>
echo "docker pull ${IMAGE}"
```

## Customise/Exntend

You can change version of R/python by specifying values in `./.env`, and then `make build`. The specified python version should be available by the latest pyenv. To install new packages, renv and poetry would be useful.

## Version info

```{sh about-linux, comment=""}
cat /etc/os-release;
cat /proc/version
```


```{r about-R, comment=""}
R.version

# R packages
library(magrittr)
installed.packages() %>%
    as.data.frame() %>%
    .[, c("Package", "Version")]
```

```{sh about-python, comment=""}
python --version;
pip list
```